name: ragqa
channels:
  - conda-forge
  - pytorch
  - huggingface
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - transformers
  - accelerate
  - sentence-transformers
  - langchain
  - langchainhub
  - chromadb
  - pip:
    - streamlit
    - pypdf